---
title: "report"
output: html_document
---

[introduction]

```{r}
par(mfrow=c(1,3))
x <- runif(50)
hist(x, main='Histogram of 50 draws')
y <- runif(500)
hist(y, main='Histogram of 500 draws')
z <- runif(5000)
hist(z, main='Histogram of 5000 draws')
```

[discussion of efficacy of random number generator]


[introduction to meat of assignment]

[B: simulating random variable S with uniformly distributed variable U]
```{r}
n<-10

sim.coin <- function(n) {
  S<-runif(n, -1, 1)
  ifelse(S < 0, -1, 1)
}

sim.coin(n)
```
[C 3650 og_cumsum(sim.coin(n))]

```{r}
n<-3650

my_cumsum <- function(x) {
  sum_vec <- cumsum(x)  # base R's cumsum is written in C — extremely fast
  positive <- sum(sum_vec > 0) / length(sum_vec)
  return(list(sum_vec, positive))
}

balance<-my_cumsum(sim.coin(n))[[1]]
plot(1:3650,balance,type='l',xlab="Number of Trials", ylab="Balance", ylim=c(-150, 150))

balance<-my_cumsum(sim.coin(n))[[1]]
lines(1:3650, balance, type='l', col='blue')

balance<-my_cumsum(sim.coin(n))[[1]]
lines(1:3650, balance, type='l', col='red')

balance<-my_cumsum(sim.coin(n))[[1]]
lines(1:3650, balance, type='l', col='pink')

```

[we expect that the balance is positive half the time, is this the case in your generated realization?]

No, because in 

[E: a graph where the balance is positive only 5 percent of the time seems highly unlikely. Make a guess at the probability of this happening]



[F:]

```{r}
pos.vec<-1:1000

for (i in 1:1000) {
  pos.vec[i]<-my_cumsum(sim.coin(n))[[2]]
}
hist(pos.vec, probability=TRUE, 
     main = "Fraction of time balance is positive",
     xlab = "Fraction positive")
x<-seq(0,1,0.01)
lines(x, 1/(pi*(sqrt(x*(1-x)))), type='l', col='brown', lwd=3)

print(mean(pos.vec))
```
[J: calculate probability we have positive balance less than 5% of time]

```{r}
sim.prob <- sum(pos.vec < 0.05) / 1000
print(sim.prob)

theoretical.prob <- (2/pi) * asin(sqrt(0.05))
print(theoretical.prob)
```
